spring.cloud.stream.defaultBinder: kafka1
spring.cloud.stream:
  function.definition: splitter;
  bindings:
    splitter-out-0:
      destination: topic-out
    splitter-in-0:
      destination: topic-in
  binders:
    kafka1:
      type: kafka


