spring.cloud.stream.defaultBinder: kafka1
spring.cloud.stream:
  function.definition: shapes;
  bindings:
    shapes-out-0:
      destination: topic-out
    shapes-in-0:
      destination: topic-in
  binders:
    kafka1:
      type: kafka


